[general]
live_config_reload = true
import = [
	"~/.config/alacritty/vague.toml"
]

[window]
dynamic_title = true
option_as_alt = "OnlyLeft"
padding = { x = 0, y = 0 }

[font]
size = 15.0
normal = { family = "Iosevka NF", style = "Regular" }
